// Operational AI Service - Core automation engine
// Executes actions automatically based on business constraints and events

import { 
  sendNotification, 
  sendCustomerNotification,
  getOwnerMobileNumber,
  type Notification 
} from './notificationService';
import { 
  checkStockLevels, 
  type StockAlert,
  markAlertAsSent 
} from './stockMonitoringService';
import { 
  checkUpcomingOccasions,
  type SpecialOccasion 
} from './specialOccasionsService';
import { 
  calculateMonthlyRevenue,
  getPreviousMonthRevenue 
} from './metricsService';
import {
  scheduleTasksFromWeeklyPlan,
  getTasksForDay,
  type ScheduledTask
} from './schedulingService';

export interface BusinessConstraints {
  timePerDay: number;
  monthlyBudget: number;
  numberOfWorkers: number;
  businessType: string;
  daysAvailable: string[];
}

export interface DailyTask {
  id: string;
  task: string;
  assignedTo: string;
  time: string;
  priority: 'low' | 'medium' | 'high';
  category: 'routine' | 'advertising' | 'stock' | 'customer' | 'festival';
  autoGenerated: boolean;
  completed: boolean;
}

// Auto-generate daily task list based on constraints
export function generateDailyTasks(constraints: BusinessConstraints, weeklyPlan?: Array<{ day: string; tasks: string[] } | { day: string; tasks: Array<{ text: string }> }>): DailyTask[] {
  const today = new Date();
  const dayName = today.toLocaleDateString('en-US', { weekday: 'long' });
  const tasks: DailyTask[] = [];

  // Check if shop is open today
  const isOpenToday = constraints.daysAvailable.includes(dayName);
  if (!isOpenToday) {
    return tasks; // No tasks if closed
  }

  // Get tasks from weekly plan if available
  if (weeklyPlan && weeklyPlan.length > 0) {
    const todayPlan = weeklyPlan.find(p => p.day === dayName);
    if (todayPlan) {
      // Handle both formats: { day, tasks: string[] } and { day, tasks: TaskItem[] }
      const taskList = todayPlan.tasks;
      
      taskList.forEach((taskItem: string | { text: string }, index: number) => {
        // Extract task text
        let taskText: string;
        if (typeof taskItem === 'string') {
          taskText = taskItem;
        } else if (taskItem && typeof taskItem === 'object' && 'text' in taskItem) {
          taskText = taskItem.text;
        } else {
          return; // Skip invalid format
        }

        // Extract worker assignment
        let assignedTo = 'You';
        if (constraints.numberOfWorkers > 1) {
          if (taskText.includes('Worker 1')) {
            assignedTo = 'Worker 1';
          } else if (taskText.includes('Worker 2')) {
            assignedTo = 'Worker 2';
          } else if (taskText.includes('Worker 3')) {
            assignedTo = 'Worker 3';
          }
        }

        const cleanTask = taskText.replace(/^(You|Worker \d+):\s*/, '');
        
        tasks.push({
          id: `daily_${dayName}_${index}_${Date.now()}`,
          task: cleanTask,
          assignedTo,
          time: getOptimalTime(cleanTask, constraints.timePerDay),
          priority: determinePriority(cleanTask),
          category: categorizeTask(cleanTask),
          autoGenerated: true,
          completed: false,
        });
      });
    }
  }

  // Add routine tasks based on constraints
  if (constraints.timePerDay >= 0.5) {
    tasks.push({
      id: `routine_check_stock_${Date.now()}`,
      task: 'Check stock levels and update inventory',
      assignedTo: constraints.numberOfWorkers > 1 ? 'Worker 1' : 'You',
      time: '09:00',
      priority: 'high',
      category: 'stock',
      autoGenerated: true,
      completed: false,
    });
  }

  if (constraints.timePerDay >= 1) {
    tasks.push({
      id: `routine_customer_service_${Date.now()}`,
      task: 'Respond to customer inquiries and reviews',
      assignedTo: constraints.numberOfWorkers > 1 ? 'Worker 2' : 'You',
      time: '10:00',
      priority: 'medium',
      category: 'customer',
      autoGenerated: true,
      completed: false,
    });
  }

  // Check for festivals/occasions and add advertising tasks
  const occasions = checkUpcomingOccasions();
  const todayOccasions = occasions.filter(occ => {
    const occDate = new Date(occ.date);
    return occDate.toDateString() === today.toDateString();
  });

  todayOccasions.forEach(occasion => {
    if (!occasion.advertisingReminders.webpage) {
      tasks.push({
        id: `festival_webpage_${occasion.id}_${Date.now()}`,
        task: `Update website with ${occasion.name} promotions`,
        assignedTo: constraints.numberOfWorkers > 1 ? 'Worker 1' : 'You',
        time: '11:00',
        priority: 'high',
        category: 'festival',
        autoGenerated: true,
        completed: false,
      });
    }

    if (!occasion.advertisingReminders.instagram) {
      tasks.push({
        id: `festival_instagram_${occasion.id}_${Date.now()}`,
        task: `Post on Instagram about ${occasion.name} special offers`,
        assignedTo: constraints.numberOfWorkers > 1 ? 'Worker 2' : 'You',
        time: '12:00',
        priority: 'high',
        category: 'festival',
        autoGenerated: true,
        completed: false,
      });
    }
  });

  return tasks.sort((a, b) => {
    const priorityOrder = { high: 3, medium: 2, low: 1 };
    return priorityOrder[b.priority] - priorityOrder[a.priority];
  });
}

// Monitor stock and send alerts automatically
export async function monitorStockAndAlert(
  products: Array<{ id: string; name: string; stock: number }>,
  ownerMobile?: string
): Promise<{ alerts: StockAlert[]; advertisingPaused: boolean }> {
  const alerts = checkStockLevels(products);
  let advertisingPaused = false;

  for (const alert of alerts) {
    if (!alert.sent) {
      const ownerNumber = ownerMobile || getOwnerMobileNumber();

      if (alert.alertType === 'exhausted') {
        // CRITICAL: Stock exhausted
        await sendNotification(
          'stock-exhausted',
          'urgent',
          '🚨 STOCK EXHAUSTED',
          `${alert.productName} is completely out of stock. Immediate action required!`,
          ownerNumber || undefined
        );

        // Send WhatsApp alert to 8825484735 (as per requirement)
        const { sendWhatsAppAlert, generateStockExhaustedAlert } = await import('@/services/whatsappAlertsService');
        const whatsappAlert = generateStockExhaustedAlert(alert.productName);
        await sendWhatsAppAlert(whatsappAlert, '8825484735');

        // Send to customers
        await sendCustomerNotification(
          'stock-alert',
          `${alert.productName} Out of Stock`,
          `We're currently out of ${alert.productName}. We'll notify you when it's back in stock!`
        );

        // Pause advertising tasks
        advertisingPaused = true;

        markAlertAsSent(alert.id);
      } else if (alert.alertType === 'critical') {
        // URGENT: Critical stock level
        await sendNotification(
          'stock-critical',
          'urgent',
          '⚠️ CRITICAL STOCK ALERT',
          `${alert.productName} has only ${alert.currentStock} units left. Stock will be exhausted soon!`,
          ownerNumber || undefined
        );

        // Send WhatsApp alert to 8825484735 (as per requirement)
        const { sendWhatsAppAlert, generateLowStockAlert } = await import('@/services/whatsappAlertsService');
        const whatsappAlert = generateLowStockAlert(alert.productName, alert.currentStock);
        await sendWhatsAppAlert(whatsappAlert, '8825484735');

        markAlertAsSent(alert.id);
      } else if (alert.alertType === 'low') {
        // HIGH: Low stock warning
        await sendNotification(
          'stock-low',
          'high',
          '📉 Low Stock Warning',
          `${alert.productName} is running low (${alert.currentStock} units remaining). Consider restocking.`,
          ownerNumber || undefined
        );

        // Send WhatsApp alert to 8825484735 (as per requirement)
        const { sendWhatsAppAlert, generateLowStockAlert } = await import('@/services/whatsappAlertsService');
        const whatsappAlert = generateLowStockAlert(alert.productName, alert.currentStock);
        await sendWhatsAppAlert(whatsappAlert, '8825484735');

        markAlertAsSent(alert.id);
      }
    }
  }

  return { alerts, advertisingPaused };
}

// Monitor sales and send alerts
export async function monitorSalesAndAlert(ownerMobile?: string): Promise<Notification | null> {
  const currentRevenue = calculateMonthlyRevenue();
  const previousRevenue = getPreviousMonthRevenue();

  if (previousRevenue > 0) {
    const dropPercentage = ((previousRevenue - currentRevenue) / previousRevenue) * 100;
    
    // Alert if sales dropped more than 20%
    if (dropPercentage > 20) {
      const ownerNumber = ownerMobile || getOwnerMobileNumber();
      
      const notification = await sendNotification(
        'sales-drop',
        'high',
        '📉 Sales Drop Alert',
        `Sales have dropped by ${dropPercentage.toFixed(1)}% compared to last month. Current: ₹${currentRevenue.toLocaleString('en-IN')}, Previous: ₹${previousRevenue.toLocaleString('en-IN')}. Review your marketing strategy.`,
        ownerNumber || undefined
      );

      return notification;
    }
  }

  return null;
}

// Check festivals and send reminders
export async function checkFestivalsAndRemind(ownerMobile?: string): Promise<Notification[]> {
  const occasions = checkUpcomingOccasions();
  const notifications: Notification[] = [];
  const ownerNumber = ownerMobile || getOwnerMobileNumber();

  for (const occasion of occasions) {
    const daysUntil = Math.ceil(
      (new Date(occasion.date).getTime() - new Date().getTime()) / (1000 * 60 * 60 * 24)
    );

    // Send reminder 3 days before
    if (daysUntil === 3) {
      const notif = await sendNotification(
        'festival-reminder',
        'high',
        `🎉 ${occasion.name} Coming Soon!`,
        `${occasion.name} is in ${daysUntil} days! Don't forget to:\n- Update your website with special promotions\n- Post on Instagram about ${occasion.name} offers\n- Prepare special products/services`,
        ownerNumber || undefined
      );
      notifications.push(notif);

      // Send promotional alert to customers
      await sendCustomerNotification(
        'festival',
        `${occasion.name} Special Offers!`,
        `🎉 ${occasion.name} is coming! Visit us for special promotions and exclusive offers. Stay tuned for updates!`
      );
    }

    // Send reminder 1 day before
    if (daysUntil === 1) {
      const notif = await sendNotification(
        'festival-reminder',
        'urgent',
        `🚨 ${occasion.name} Tomorrow!`,
        `${occasion.name} is TOMORROW! Make sure you've:\n- Updated website\n- Posted on Instagram\n- Prepared special items`,
        ownerNumber || undefined
      );
      notifications.push(notif);
    }
  }

  return notifications;
}

// Helper functions
function getOptimalTime(task: string, timePerDay: number): string {
  const lower = task.toLowerCase();
  if (lower.includes('check') || lower.includes('stock')) return '09:00';
  if (lower.includes('customer') || lower.includes('review')) return '10:00';
  if (lower.includes('social') || lower.includes('instagram')) return '11:00';
  if (lower.includes('advertising') || lower.includes('promotion')) return '12:00';
  return '09:00';
}

function determinePriority(task: string): 'low' | 'medium' | 'high' {
  const lower = task.toLowerCase();
  if (lower.includes('stock') || lower.includes('urgent') || lower.includes('critical')) return 'high';
  if (lower.includes('customer') || lower.includes('review') || lower.includes('advertising')) return 'medium';
  return 'low';
}

function categorizeTask(task: string): DailyTask['category'] {
  const lower = task.toLowerCase();
  if (lower.includes('stock') || lower.includes('inventory')) return 'stock';
  if (lower.includes('instagram') || lower.includes('social') || lower.includes('advertising')) return 'advertising';
  if (lower.includes('customer') || lower.includes('review')) return 'customer';
  if (lower.includes('festival') || lower.includes('occasion') || lower.includes('promotion')) return 'festival';
  return 'routine';
}
